image: maven:3.6.3-jdk-11

stages:
  - package
  - test
  - deploy

package app:
  stage: package
  cache:
    key: app_cache
    policy: push
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2 hrs
    paths:
      -  ./target/spring-petclinic-2.6.0-SNAPSHOT.jar
  script:
    - mvn clean package
  tags: 
    - docker

test app:
  stage: test
  script:
    - mvn test
  tags:
    - docker

deploy app:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/cbarbieri-spring-petclinic.git
    - git push -f heroku HEAD:master 
    - echo "Deployed to Staging Server https://cbarbieri-spring-petclinic.herokuapp.com/"
  environment:
    name: staging
    url: https://cbarbieri-spring-petclinic.herokuapp.com/
  only:
    - main
  tags:
    - docker 




