image: openjdk:8-jdk

stages:
  - test
  - package
  - deploy

test app:
  stage: test
  before_script:
    - ./mvnw install  
  script:
    - ./mvnw spring-boot:run &
    - sleep 120
    - curl http://localhost:8080
  tags: 
    - docker

package app:
  stage: package
  cache:
    key: app_cache
    policy: push
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2 hrs
    paths:
      -  ./target/*.jar
  script:
    - ./mvnw package
  tags: 
    - docker

deploy app:
  image: ruby:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none
  cache:
    key: app_cache
    policy: pull
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  environment:
    name: prd
  only:
    - main
  tags: 
    - docker



