image: openjdk:11.0

stages:
  - test
  - package
  - deploy

test app:
  stage: test
  before_script:
    - ./mvnw install
  script:
    - ./mvnw spring-boot:run &
    - sleep 120
    - curl http://localhost:8080
  tags: 
    - docker

package app:
  stage: package
  cache:
    key: app_cache
    policy: push
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2 hrs
    paths:
      -  ./target/*.jar
  before_script:
    - ./mvnw install
  script:
    - ./mvnw package
  tags: 
    - docker

deploy app:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  cache:
    key: app_cache
    policy: pull
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/spring-petclinic-cbarbieri.git
    - echo "Deployed to Heroku"
  environment:
    name: prd
    url: https://spring-petclinic-cbarbieri.herokuapp.com/
  only:
    - main
  tags: 
    - docker



