image: openjdk:11.0

stages:
  - test
  - package
  - deploy

test app:
  stage: test
  script:
    - ./mvnw spring-boot:run &
    - sleep 120
    - curl http://localhost:8080
  tags: 
    - docker

package app:
  stage: package
  cache:
    key: app_cache
    policy: push
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2 hrs
    paths:
      -  ./target/*.jar
  before_script:
    - ./mvnw install
  script:
    - ./mvnw package
  tags: 
    - docker

deploy app:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  cache:
    key: app_cache
    policy: pull
  script:
  #   - apt-get update -yq
  #   - apt-get install -y ruby-dev
  #   - gem install dpl 
  #   - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    - ./mvnw clean heroku:deploy-war
  environment:
    name: prd
  only:
    - main
  tags: 
    - docker



