image: openjdk:11-jdk-oracle

stages:
  - test
  - package
  - deploy

test app:
  stage: test
  before_script:
    - ./mvnw install
  script:
    - ./mvnw spring-boot:run
    - curl http://localhost:8080
  cache:
    key: app_cache
    policy: push
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2 hrs
    paths:
      -  ./target/*.jar

package app:
  stage: package
  cache:
    key: app_cache
    policy: pull
  script:
    - ./mvnw package

deploy app prd:
  image: node:latest
  stage: deploy
  variables:
    CNAME: spring-petclinic-deploy.sh
    GIT_STRATEGY: none
  cache:
    key: app_cache
    policy: pull
  before_script:
    - npm install -g surge
  script:
    -surge --project ./target --domain ${CNAME}
  environment:
    name: prd
    url: http://${CNAME}
  only:
    - master



